# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://caoshipeng1991.github.io
date_format: "ordinal"
title: Russell
subtitle: "Russell"
description: "Russell"
keywords: Russell，
timezone: Asia/YangLing
encoding: "utf-8"
side_bar_repo_limit: 8
repository: caoshipeng1991/caoshipeng1991.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
 #    busuanzi:
 #       enabled: true
 #       start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Russell
organization: 
organization_url: 
github_username: Russell
location: SZ, China
email: russellcao@tencent.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /archives/
    label: 归档

  -
    href: /categories/
    label: 分类

#   -
#     href: /open-source/
#     label: 开源

#   -
#     href: /wiki/
#     label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于
#  -
#    href: /domains/
#    label: 域名

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:title.html
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#     username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: mzlogin
#     repo: blog-comments
#     oauth:
#        client_id: d2e1cbbd2989
#         client_secret: b42a41
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

